### ISSUE TITLE
request: multiple devices + input ? / console ? 

### ISSUE THREAD

**Issue by mr4hughz** [Funbit/ets2-telemetry-server#22]
use of multiple skin/devices (tablet + phone+ phone 2) 
1 screen for gauges (phone) 
other screen (tablet example)  for cruisecontrole/fuel or other buttons/settings and what not ..  
load with skin per device (configurable) 

change radio/or other in game settings would be nice .. (if possible) 

keep up the great work ! (thx)

**Comment by Funbit** [comment]
I'm not sure that I understood your suggestion correctly.
The current version of the dashboard does support multiple devices displaying different skins. It is just there are not enough skins now (for example, a skin for speedometer and tachometer only, a skin for job info, etc). Maybe I or somebody else will eventually create such skins. I'm going to publish a simple skin creation tutorial soon, so I hope people will help me with this.

As for the radio, I like the idea. The telemetry plugin itself does not control the game, but I could transfer some actions from a device to the telemetry server so that the server will emulate some keystrokes, like a button that switches the radio. I will think about this in the future versions, because this is not a simple feature and will take a significant amount of time.

And thanks for the thanks ;)
