### ISSUE TITLE
Why require activating before hand?

### ISSUE THREAD

**Issue by sislamoglu** [Funbit/ets2-telemetry-server#62]
There is another plugin here..

It does not require you to activate it to send data to its Android client... Why this one requires extra tool to activate server?

Can't it be automatic when plugin activated with game?

https://www.youtube.com/watch?v=yhL7TDarAME&feature=youtu.be

http://forum.wotr.pl/showthread.php?tid=8961

**Comment by Funbit** [comment]
Technically, it is possible to combine telemetry plugin and web server into a single DLL. But:

1. The server solution is written in C# based on .NET Framework stack. It is not easy to join unmanaged and managed DLLs, which would require to load .NET Framework into game's process. Moreover, the web server would make a direct impact on the game and I wanted to avoid that. 
2. The server has its own UI. If I move web server handling code into telemetry plugin itself it raises a question about UI.
3. The current way is much easier to manage, because server can be put (and moved) in any folder. As you can see in the video you provided - there are many manual copy/paste steps to setup everything and average users are not able to perform that without making errors (trust me on that). The server provides automated setup for them.
