### ISSUE TITLE
converting full estimated distance into user friendly format

### ISSUE THREAD

**Issue by dualznz** [Funbit/ets2-telemetry-server#77]
Hi all

I am unsure how to convert the Estimated Distance from likes of 2429998.91

which is really only 242 kms but the data feed is showing full

any help would be great, im confused on this one little thing

**Comment by mike-koch** [comment]
The telemetry server returns distances in meters (which is why you're seeing the 2429998.91). If you want to convert it, you will need to do some calculations by hand, like this (the below code is in JavaScript, but it should be similar to any other language):

```javascript
var estimatedDistanceKm = data.navigation.estimatedDistance / 1000;
```

If you want to drop everything after the decimal place, you can use something like this:

```javascript
var estimatedDistanceKm = Math.floor(data.navigation.estimatedDistance / 1000);
```

**Comment by dualznz** [comment]
cheers for the reply its now showing in this case 591782  which is 591, i really would like to remove the 782 as its not needed, any ideas?

cheers

**Comment by mike-koch** [comment]
If you divide the value by 1000, and then use `Math.floor`, it should return 591. See https://jsfiddle.net/um0euukk/.

**Comment by Funbit** [comment]
I suppose the topic may be closed.
