### ISSUE TITLE
job data does not reset on job completion

### ISSUE THREAD

**Issue by dualznz** [Funbit/ets2-telemetry-server#81]
The job data still remains place after completing the job, how can i fix this from doing this

**Comment by Funbit** [comment]
When you finish your job inside the game and see main screen with your truck - the job information inside telemetry dashboard will still be there, this is not a bug, but an acceptable workaround (since original telemetry SDK does not reset job info by itself). 
However, as soon as you enter the game again by pressing the [DRIVE] button at the lower left corner (doesn't matter whether you get a new job or just go with empty truck) - the job information should be reset at this point. Please check this and let me know if it still does not work for you.

**Comment by dualznz** [comment]
hi thanks for the reply, i have just checked and after i complete the job, click on show results then click on drive the api is still showing the job is still in place and hasnt reset the information.

**Comment by Funbit** [comment]
Since I can't reproduce it on my side, could you please provide the following information:
- game name (ETS2 or ATS)
- type of the job (quick job, freight market or contract)
- do you finish your job in one shot or do save/load ?

**Comment by dualznz** [comment]
ets2
freight market
source city and destination is the same city
fps 60+ consistant.

**Comment by Funbit** [comment]
Thanks, I see now. The thing is that there are several conditions have to be satisfied in order for the job to clear, and the current method I use does not support cases when distance between source and destination is less than 500m. 
Since users usually don't get so simple jobs (only for tests maybe), I thought that this behavior is acceptable.
Please try to get a job when destination is in another city and see if it works.

PS. I will try to find the most optimal distance to cover all possible cases, maybe 500m is too much (however, 100m is not enough either)..

**Comment by dualznz** [comment]
i recon it would amount to less than 10 meters as the trailer will be stapled within the 10 meter wall, and i also did try from another city with the same result.

**Comment by Funbit** [comment]
Well, not exactly. The game stops updating navigation distance as soon as you close to the destination point (when you see a message asking for auto-park). Sometimes the distance value stops at 100m, sometimes 250m. After many tests I have found out that 500m is the optimal value.
Anyway, the problem you are experiencing should not be related to the distance at all. I have refactored job reset code and updated server (3.2.5). Please try the new version.
I have completed around 20 different jobs, including same source-destination, quick/market, auto/manual parking, etc. Everything works as expected.

PS. Once again, please note that when you finish your job using auto-parking feature, the game does not update "trailer attached" value, which causes job info not being reset even if you already see main game menu. However, it will reset as soon as you enter the game again (taking a new job or just drive an empty truck).

Cheers.

**Comment by dualznz** [comment]
update worked perfectly cheers
